import Head from "next/head";
import React from "react";

const HeadTitle = ({ title }) => {
  return (
    <Head>
      <title>Super Cargo | | {title}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="shortcut icon" href="Supercargo.jpg" />
    </Head>
  );
};

export default HeadTitle;
